Sprint2/step2
MrPhysix/react-burger pull request #5
Opened 2022-11-20 19:24 UTC by MrPhysix

Я не понял про какой счетчик шла речь в задании, drag & drop в конструкторе работает, но через раз (я без понятия почему)

2022-11-21 03:10 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Реализована работа с redux;
- Реализован функционал с DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- У вас некорректно реализована работа с Dnd:

  - Если попробовать перетащить элемент, то после того как мы прекратим это делать, элемент перетаскивать больше нельзя: https://disk.yandex.ru/i/0oB64fjDFquEgw;

  - Элементы не меняют своего положения, как это должно быть: https://disk.yandex.ru/i/7gFf2HTpHeq5Dg;

- В компоненте App-header требуется поправить семантику, переделать button в ссылки.
  А также нужно убрать подписчик на событие `handleClick`.
  Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

  Например

  ```html
  <a href="#" class="......"> <BurgerIcon type="primary" /> Конструктор </a>
  ```

  В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

- В приложении не должно быть `console.log`;

- По чек-листу, у вас должна быть папка `services` и там должна располагаться работа с Redux.

- По чек-листу: Для каждого экшена, который связан с запросом к Api создан усилитель. Для таких экшенов описан тип \_REQUEST, тип \_SUCCESS, \_ERROR. Чтобы это реализовать используйте `createReducer вместе с builder`: https://redux-toolkit.js.org/api/createReducer#overview.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/App/App.tsx
> +        .finally(() => setIsLoading(false));
**Надо исправить:**

Вся работа с сервером, на данный момент, должна выполняться через redux, с использованием thunk (асинхронных экшенах).

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/App/App.tsx
> +        <ConstructorContext.Provider value={constructorContextValue}>
**Надо исправить:**

На данном этапе вы должны использовать только redux. Любое дублирование функционала, это всегда не очень хорошо.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/App/App.tsx
> +            ? <CirclesWithBar width="82" color="#4C4CFF" ariaLabel="loading" wrapperClass="loading-spinner" />
**Надо исправить:**

Цвет лучше вынести в константу. Также как и ширину. В идеале это всё сделать через классы.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructorElement/BurgerConstructorElement.js
>  BurgerConstructorElement.propTypes = {
**Надо исправить:**

Описаны не все пропсы, которые используются в компоненте.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +    const generatedId = uuidv4();
**Можно лучше:**

Лучше сразу генерировать id в поле, не нужно создавать отдельную переменную для этого. А вообще, т.к. у вас может быть множество способов добавления ингредиента в конструктор (в теории). И чтобы не дублировать эту запись, лучше всего делать это в action-creator.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  } : {};
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  ), []);
**Надо исправить:** 

Не используйте тут useCallback, он нужен немного для других целей, рендерите напрямую в `jsx`.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +            <Modal handleClose={() => handleOrderModal.close()}>
**можно лучше:** 

Можно сделать без анонимной функции.

```js
handleClose={handleOrderModal.close}
```

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientCard/IngredientCard.js
>  IngredientCard.propTypes = {
**Надо исправить:**

Описаны не все пропсы, которые используются в компоненте.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList/IngredientsList.js
>  IngredientsList.propTypes = {
**Надо исправить:**

Описаны не все пропсы, которые используются в компоненте.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList/IngredientsList.js
> +  ingredients: PropTypes.arrayOf(ingredientPropTypes).isRequired,
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.js
> +          <Tab value="bun" active={current === INGREDIENT_TYPES.BUN.TYPE} onClick={() => scrollToList(bunRef) && setCurrent}>
**Надо исправить:** 

Лучше вынести в отдельный обработчик событий, а не писать так.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.js
> +      setCurrent(() => {
**Надо исправить:**

нужно убрать обёртку в виде `setCurrent`. Она тут лишняя, вы не используете функциональное обновление.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.js
> +      { ingredientDetails.item !== {} && ingredientDetails.isOpen && (
**Надо исправить:** 

Если `ingredientDetails.item` будет объектом, то условие `ingredientDetails.item !== {}` всегда будет `true`. Проверяйте на null.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/Modal/Modal.js
> +  const handleCloseByKey = (evt) => (evt.key === 'Escape') && handleClose() && evt.target.blur();
**Надо исправить:**

ЛУчше писать функции друг за другом, а не через `&&`. 
Это намного повышает читабельность кода.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/Modal/Modal.js
> +  const jsx = (
**Можно лучше:**

Это конечно хорошо, что вы вынесли структуру. Но лучше сразу в `createPortal` делать рендер, т.к вы не переиспользуйте код.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/components/Modal/ErrorModal/ErrorModal.js
> +function ErrorModal({ handleClose }) {
**Надо исправить:**

для этого компонента так же нужно описать PropTypes

2022-11-21 03:10 UTC, ArslanMustafin commented on src/store/reducers/ingredientDetails.js
> +  item: {},
**Надо исправить:**

Если данных нет, то следует записывать null а не пустой объект.

2022-11-21 03:10 UTC, ArslanMustafin commented on src/store/reducers/ingredientDetails.js
> +  reducers: {
**Можно лучше:**

Стоит добавить очистку поля `item`, например использовать это при закрытии модального окна.

2022-11-21 12:08 UTC, MrPhysix commented on src/components/App/App.tsx
> +            ? <CirclesWithBar width="82" color="#4C4CFF" ariaLabel="loading" wrapperClass="loading-spinner" />
это библиотечный компонент....

2022-11-22 02:28 UTC, ArslanDev666 commented on src/components/App/App.tsx
> +            ? <CirclesWithBar width="82" color="#4C4CFF" ariaLabel="loading" wrapperClass="loading-spinner" />
```jsx
<CirclesWithBar ariaLabel="loading" wrapperClass={styles.spinner} />
```

```css
.spinner {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 90vh;
}
.spinner svg {
  width: 82px;
}
.spinner svg circle {
  stroke: #4c4cff;
}

.spinner svg g {
  fill: #4c4cff;
}

```

Мне кажется то, что это библиотечный компонент, не сильно мешает классу перебивать стили))

2022-11-22 09:27 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Практические все замечания с прошлого ревью были исправлены

### **Вы молодец!**

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- У вас некорректно реализована работа с Dnd:

  - При перетаскивании элемента у вас меняются местами только первые 2 элементы или не меняются вообще, вообщем странное очень поведение, еще раз проверьте алгоритм работы пересортировки элементов: https://disk.yandex.ru/d/wKVkVmaziJEFiQ;

  - При перетаскивании булок в `burgerConstructor` в консоли возникают ошибки: https://yadi.sk/d/dRebcC6C-scFFw;

  Привильный вариант работы DnD: https://disk.yandex.ru/i/7gFf2HTpHeq5Dg;

- В приложении не должно быть `console.log`;

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. Компоненты: `BurgerConstructor`, `BurgerConstructorElement`.

- В propTypes описаны не все пропсы, которые используются в компоненте `IngredientCard.js`: не описан пропс `onClick`.

- В propTypes описаны не все пропсы, которые используются в компоненте `IngredientsList.js`: не описан пропс `onIngredientClick`.

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Компонент: `IngredientsList`;

- Нужно обязательно исправить данное замечание, https://github.com/MrPhysix/react-burger/pull/5#discussion_r1027498334, лишняя обёртка вызывает очень много ререндеров)

- Если ingredientDetails.item будет объектом, то условие ingredientDetails.item !== {} всегда будет true. Проверяйте на null. - Компонент: `BurgerIngredients`.

### **_Подробно эти и более мелкие замечания, были отмечены в коде._**

2022-11-22 09:27 UTC, ArslanMustafin commented on src/components/App/App.jsx
> +  }, [ingredients.status]);
**Можно лучше:**

Почему бы сразу не сделать проверку на `ingredients.status`, а не использовать допольнительные стейты.

Loading - если состояние `request`.
Показывать только ошибку если `error`, 
и т.д

2022-11-22 09:27 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.js
> +            onIngredientClick={() => handleDetailsModal}
**Надо исправить:**

Здесь и далее, пишите просто `onIngredientClick={handleDetailsModal}` Тут не нужно использовать стрелочную функцию, вы ничего не передаёте в `handleDetailsModal`.

2022-11-22 09:27 UTC, ArslanMustafin commented on src/components/BurgerIngredients/IngredientsList/IngredientsList.js
> +              onClick={onIngredientClick()}
**Надо исправить:** 

не стоит вызывать функцию в обработчике событий, лучше просто указать: `onClick={onIngredientClick}`, и всё будет работать также (При условии, что вы также исправили замечание с данной функции в компоненте выше).

2022-11-22 18:44 UTC, MrPhysix commented on src/components/BurgerIngredients/BurgerIngredients.js
> +      setCurrent(() => {
Ой))

2022-11-23 05:03 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

2023-01-09 11:36 UTC, merged